TF_IA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('som.urls')),
]

som/urls.py
from django.urls import path
from .views import *

app_name = 'som'

urlpatterns = [
    path('', ListPatient.as_view(), name='list_patient'),
    path('patient/register/', CreatePatient.as_view(), name='register_patient'),
    path('patient/edit/<int:pk>', EditPatient.as_view(), name='edit_patient'),
    #path('patient/diagnostic/', DiagnosticPatient.as_view(), name='diagnostic_patient'),
    path('patient/diagnosticar/<int:id>', diagnostic, name='hallarPaciente'),
]

som/models.py
from django.db import models

# Create your models here.

class Patient(models.Model):

    CHOICE_SEX = (
        (0,('MASCULINO')),
        (1, ('FEMENINO'))
    )
    CHOICE_CP = (
        (1, 'Angina típica'),
        (2, 'Angina atípica'),
        (3,'Sin dolor de angina'),
        (4,'asintomático')
    )
    CHOICE_FBS = (
        (0, 'VERDADERO'),
        (1, 'FALSO')
    )
    CHOICE_RESTECG = (
        (0, 'normal'),
        (1, 'anormal'),
        (2, 'probable hipertrofia ventricular')
    )
    CHOICE_SLOPE = (
        (1, 'bajo'),
        (2, 'medio'),
        (3, 'alto')
    )
    CHOICE_THAL = (
        (3, 'normal'),
        (6, 'defecto solucionable'),
        (7, 'defecto reversible')
    )
    CHOICE_EXANG = (
        (0, 'no'),
        (1, 'si')
    )
    CHOICE_CA = (
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3)
    )

    age = models.PositiveSmallIntegerField("Edad")
    sex = models.IntegerField("Sexo",choices=CHOICE_SEX)
    cp = models.IntegerField("Dolor de pecho",choices=CHOICE_CP)
    trestbps = models.PositiveIntegerField("Presión de sangre")
    chol = models.PositiveIntegerField("Colesterol")

    fbs = models.IntegerField("Nivel de azúcar en ayuno",choices=CHOICE_FBS)
    
    restecg = models.IntegerField("Res. electrocardiográficos",choices=CHOICE_RESTECG)
    thalach = models.PositiveIntegerField("Nivel maximo de frecuencia cardiaca")
    exang = models.IntegerField("Angila inducida por ejercicio",choices=CHOICE_EXANG)
    oldpeak = models.PositiveIntegerField("Depresión ST inducida")
    slope = models.IntegerField("Pico más alto",choices=CHOICE_SLOPE)
    ca = models.IntegerField("Núm vasos principales",choices=CHOICE_CA)
    thal = models.IntegerField("thal",choices=CHOICE_THAL)
    result = models.IntegerField("Resultado", null=True, blank=True)

    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"
        db_table = "pacientes"

    def __str__(self):
        return f"{self.age} - {self.sex} - {self.cp} - {self.trestbps} - {self.chol} - {self.fbs} - {self.restecg} - {self.thalach} - {self.exang} - {self.oldpeak} - {self.slope} - {self.ca} - {self.thal} - {self.result}"

som/forms.py
from django import forms
from .models import *


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'

        widget = {
            'age': forms.IntegerField(min_value=0),
            'sex': forms.IntegerField(),
            'cp': forms.IntegerField(),
            'trestbps': forms.IntegerField(min_value=0),
            'chol': forms.IntegerField(min_value=0),
            'fbs': forms.IntegerField(),
            'restecg': forms.IntegerField(),
            'thalach': forms.IntegerField(min_value=0),
            'exang': forms.IntegerField(),
            'oldpeak': forms.IntegerField(min_value=0),
            'slope': forms.IntegerField(),
            'ca': forms.IntegerField(),
            'thal': forms.IntegerField()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': "form-control"
                }
            )

som/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, ListView, CreateView
import matplotlib.pyplot as plt
import os
import numpy as np
from django.template import Template, Context


# Create your views here.


class SOM:
    data = out = weight = None

    def __init__(self, dim, rows, col, factor, itera):
        self.dimension = dim
        self.rows = rows
        self.cols = col
        self.learning_factor = factor
        self.iterations = itera

    def training_Data(self, file):
        file = os.path.realpath(file)
        self.data = np.loadtxt(file, delimiter=",",
                               usecols=range(0, self.dimension),
                               dtype=np.float64)
        self.out = np.loadtxt(file, delimiter=",", usecols=[self.dimension],
                              dtype=np.float64)
        self.weight = np.random.randn(self.rows, self.cols, self.dimension)

    def learning_algorithm(self, dato):

        def BMU(pattern):
            result = (0, 0)
            shortest_distance = 1.0e20

            for row in range(self.rows):
                for col in range(self.cols):
                    dist = np.linalg.norm(
                        self.weight[row][col] - self.data[pattern])
                    if dist < shortest_distance:
                        shortest_distance = dist
                        result = (row, col)

            return result

        def BMU_DATA(dato):
            result = (0, 0)
            shortest_distance = 1.0e20

            for row in range(self.rows):
                for col in range(self.cols):
                    dist = np.linalg.norm(self.weight[row][col] - dato)
                    if dist < shortest_distance:
                        shortest_distance = dist
                        result = (row, col)

            return result

        def manhattan_distance(r1, c1, r2, c2):
            return np.abs(r1 - r2) + np.abs(c1 - c2)

        def most_common(lst, n):
            if len(lst) == 0: return -1
            counts = np.zeros(shape=n, dtype=np.int)
            for i in range(len(lst)):
                counts[int(lst[i])] += 1
            return np.argmax(counts)

        def find_result(mapa, Rows, Cols, bmu_row_data, bmu_col_data):
            salida = None
            delta_aumento = 1
            x = bmu_row_data
            y = bmu_col_data
            while salida is None or delta_aumento < Rows + 2:
                for i in range(delta_aumento):
                    for j in range(delta_aumento):
                        if Rows > x + i >= 0 and Cols > y + j >= 0:
                            if len(mapa[x + i][y + j]) > 0:
                                salida = mapa[x + i][y + j][0]
                                print("salida")
                                return int(salida)

                x -= 1
                y -= 1
                delta_aumento += 2
            return salida

        def display_result(dato):

            print("entrada:", dato)
            (bmu_row_data, bmu_col_data) = BMU_DATA(dato)

            maps = np.empty(shape=(self.rows, self.cols), dtype=object)

            for row in range(self.rows):
                for col in range(self.cols):
                    maps[row][col] = []

            for pattern in range(len(self.data)):
                (row, col) = BMU(pattern)
                maps[row][col].append(self.out[pattern])

            label_pesos = np.zeros(shape=(self.rows, self.cols), dtype=np.int)
            for i in range(self.rows):
                for j in range(self.cols):
                    label_pesos[i][j] = most_common(maps[i][j], 20)
            plt.imshow(label_pesos)
            plt.colorbar()
            plt.savefig("test.png")
            return find_result(maps, self.rows, self.cols, bmu_row_data,
                               bmu_col_data)

        max_range = self.rows + self.cols

        for itera in range(self.iterations):
            alfa = 1.0 - (itera * 1.0) / self.iterations
            alfaActual = alfa * self.learning_factor
            neighbors = (int)(alfa * max_range)

            learning_pattern = np.random.randint(len(self.data))
            (bmu_row, bmu_col) = BMU(learning_pattern)

            for col in range(self.cols):
                for fil in range(self.rows):
                    if manhattan_distance(bmu_row, bmu_col, col,
                                          fil) < neighbors:
                        self.weight[col][fil] += alfaActual * (
                                self.data[learning_pattern] -
                                self.weight[col][fil])

        return display_result(dato)


class ListPatient(ListView):
    model = Patient
    template_name = 'som/patient.html'


class CreatePatient(SuccessMessageMixin, CreateView):
    model = Patient
    template_name = 'som/patient_form.html'
    form_class = PatientForm
    success_url = reverse_lazy('som:list_patient')
    success_message = "Paciente creado satisfactoriamente"


class EditPatient(SuccessMessageMixin, UpdateView):
    model = Patient
    template_name = 'som/patient_form.html'
    form_class = PatientForm
    success_url = reverse_lazy('som:list_patient')
    success_message = "Paciente editado satisfactoriamente"

"""
def DiagnosticPatient(request, ListView):
    model = Patient
    template_name = 'som/patient_diagnostic.html'
    form_class = PatientForm
    success_url = reverse_lazy('som:list_patient')
"""

def execute(dato):
    np.random.seed(1)
    som = SOM(13, 60, 60, 0.2, 1500)
    som.training_Data(".../static/texto/cardiaca.txt")
    return som.learning_algorithm(dato)


def diagnostic(request, id):
    patient = Patient.objects.get(id=id)
    print(patient.result)

    if patient.result is None:
        data = [float(patient.age), float(patient.sex), float(patient.cp),
                float(patient.trestbps), float(patient.chol),
                float(patient.fbs), float(patient.restecg), float(patient.thalach),
                float(patient.exang),
                float(patient.oldpeak), float(patient.slope), float(patient.ca),
                float(patient.thal)]
        result = execute(data)
        response = str(result)
        patient.result = response
        patient.save()
        print(response)
    else:
        response = patient.result

    return render(request, 'som/patient_diagnostic.html',
                  {'response': response})

som/templates/som/patient.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Diagnosticar anemia | SOM{% endblock title %}

{% block subtitle %}
<i class="fas fa-hospital-user"></i><strong>Paciente</strong> <i class="fas fa-angle-double-right"></i>
<strong>Diagnosticar anemia</strong>
{% endblock subtitle %}

{% block content %}

<div class="card my-5">
  <div class="card-header">
    <span class="float-md-left text-black text-uppercase mt-2"><i class="fas fa-list"></i> <strong><mark> Listado de
        Pacientes registrados</mark></strong></span>

      <a href="#" onclick="return abrir_modal('{% url 'som:register_patient' %}')" class="btn btn-success float-right">
          <i class="far fa-plus-square mr-1"></i> <strong>Nuevo Paciente</strong></a>
  </div>
  <div class="card-body">
    <div class="row d-flex justify-content-center">
      <div class="col-12">
        <!--<hr class="my-3">-->
        <div class="table-responsive">
          <table id="example" class="table table-bordered table-hover text-center">
            <thead class="text-center text-white" style="background: #284b63">
              <tr>
                <th>Edad</th>
                <th>Sexo</th>
                <th>Dolor de pecho</th>
                <th>Presión de sangre</th>
                <th>Colesterol</th>
                <th>Nivel de azúcar en ayuno</th>
                <th>Resultadps electrocardiográficos en reposo</th>
                <th>Nivel máximo de frecuencia cardiaca</th>
                <th>Angila inducida por ejercicio</th>
                <th>Depresión ST inducida</th>
                <th>Pico más alto</th>
                <th>Núm. vasos principales</th>
                <th>thal</th>
                <th>Nivel de obstrucción arterial</th>
              </tr>
            </thead>
            <tbody>
              {% for paciente in object_list %}
              <tr>
                <td>{{paciente.age}}</td>
                <td>{{paciente.get_sex_display}}</td>
                <td>{{paciente.get_cp_display}}</td>
                <td>{{paciente.trestbps}}</td>
                <td>{{paciente.chol}}</td>
                <td>{{paciente.get_fbs_display}}</td>
                <td>{{paciente.get_restecg_display}}</td>
                <td>{{paciente.thalach}}</td>
                <td >{{paciente.get_exang_display}}</td>
                <td>{{paciente.oldpeak}}</td>
                <td>{{paciente.get_slope_display}}</td>
                <td>{{paciente.get_ca_display}}</td>
                <td>{{paciente.get_thal_display}}</td>
                  {% if paciente.result is None %}
                      <td>
                    <a href="{% url 'som:hallarPaciente' paciente.id %}" class="btn btn-success" ><strong><i
                                class="fas fa-share-square"></i> Diagnosticar</strong></a>
                    </td>
                  {% else %}
                      {% if paciente.result  ==  0 %}
                          <td>40%</td>
                      {% elif paciente.result == 1 %}
                          <td>50%</td>
                      {% elif paciente.result == 2 %}
                          <td>65%</td>
                      {% elif paciente.result == 3 %}
                          <td>70%</td>
                      {% elif paciente.result == 4 %}
                          <td>75%</td>
                      {% endif %}
                  {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
    <hr class="my-3">
    <br>
    <div class="d-flex justify-content-center">

        <div class="row">
            <hr class="mx-5">
            <img src="/static/image/doctor.jpg" width="40%" />
        </div>

    </div>
<hr class="my-3">
</div>


{% endblock content %}

{% block js %}
<script src="{% static 'js/table.js' %}"></script>

<script>
  $.extend(true, $.fn.dataTable.defaults, {
    searching: true,
    ordering: false,
  });
</script>
{% endblock js %}

som/templates/som/patient_diagnostic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Diagnosticar anemia | SOM{% endblock title %}

{% block content %}
    <hr class="my-3">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="card shadow">
                <div class="card-header p-1">
                  <div class="card-body">
                      <h2 class="bg-light">Diagnostico del paciente</h2>
                      <hr class="my-2">
                      <br>
                      <div class="col-12">
                        <h3>Probabilidad de sufrir una enfermedad del corazón </h3>
                          {% if response  == "0" %}
                              <h5>El diagnostico es:  Nivel de obstrucción arterial al 40%</h5>
                          {% elif response == "1" %}
                                <h5>El diagnostico es:  Nivel de obstrucción arterial al 50%</h5>
                          {% elif response == "2" %}
                                <h5>El diagnostico es:  Nivel de obstrucción arterialal 65%</h5>
                          {% elif response == "3" %}
                                <h5>El diagnostico es:  Nivel de obstrucción arterial al 70%</h5>
                          {% elif response == "4" %}
                              <h5>El diagnostico es:  Nivel de obstrucción arterial al 75%</h5>
                          {% endif %}
                      </div>
                      <div class="d-flex justify-content-center">
                            <div class="row">
                                <hr class="mx-5">
                                <img src="/static/image/test.png" width="75%" />
                            </div>
                        </div>
                      <div class=" row">

                          <div class="col-2">
                              <a href="{% url 'som:list_patient' %}" class="btn btn-danger my-3 mx-3"><i class="fas fa-window-close"></i>
                                  <strong>Cancelar</strong></a>
                          </div>
                      </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
<script src="{% static 'js/table.js' %}"></script>

<script>
  $.extend(true, $.fn.dataTable.defaults, {
    searching: true,
    ordering: false,
  });
</script>
{% endblock js %}

som/templates/som/patient_form.html
<div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content">
      <div class="row p-2">
        <div class="col">
          <div class="card shadow">

            {% if object %}
            <div class="card-header bg-warning p-1">
              {% else %}
              <div class="card-header bg-success p-1">
                {% endif %}
              </div>
              <div class="card-body">
                {% if object %}
                <form method="POST" action="{% url 'som:edit_patient' object.pk %}">
                  {% csrf_token %}
                  <div class=" row">
                    <div class="col-12">
                      <label><strong><span class="text-uppercase">Editar Paciente</span></strong></label>
                      {% else %}
                      <form method="POST" action="{% url 'som:register_patient' %}">
                        {% csrf_token %}

                        <div class=" row">
                          <div class="col-12">
                            <label><strong><span class="text-uppercase">Nuevo Paciente :</span></strong></label>
                            {% endif %}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.age.label}} :</strong></label>
                            {{form.age}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.sex.label}} :</strong></label>
                            {{form.sex}}
                          </div>
                         <div class="col-4">
                            <label><strong>{{form.cp.label}} :</strong></label>
                            {{form.cp}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.trestbps.label}} :</strong></label>
                            {{form.trestbps}}
                          </div>

                          <div class="col-4">
                            <label><strong>{{form.chol.label}} :</strong></label>
                            {{form.chol}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.fbs.label}} > 120:</strong></label>
                            {{form.fbs}}
                          </div>
                         <div class="col-4">
                            <label><strong>{{form.restecg.label}} :</strong></label>
                            {{form.restecg}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.thalach.label}} :</strong></label>
                            {{form.thalach}}
                          </div>

                          <div class="col-4">
                            <label><strong>{{form.exang.label}} :</strong></label>
                            {{form.exang}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.oldpeak.label}} :</strong></label>
                            {{form.oldpeak}}
                          </div>
                         <div class="col-4">
                            <label><strong>{{form.slope.label}} :</strong></label>
                            {{form.slope}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.ca.label}} :</strong></label>
                            {{form.ca}}
                          </div>
                          <div class="col-4">
                            <label><strong>{{form.thal.label}} :</strong></label>
                            {{form.thal}}
                          </div>
                        </div>
                        <div class=" row">
                            <div class="col-2">
                                <br>
                              <button type="submit" class="btn btn-info"><strong><i class="fas fa-save"></i>
                                  Guardar</strong></button>
                            </div>
                            <div class="col-2">
                                <br>
                              <button type="submit" class="btn btn-danger" onclick="return cerrar_modal()"><strong><i
                                    class="fas fa-window-close"></i>
                                  Cancelar</strong></button>
                            </div>
                        </div>
                      </form>
                    </div>
                  </div>
              </div>
            </div>

          </div>
        </div>